### ISSUE TITLE
unable to run it

### ISSUE THREAD

**Issue by moovida** [LinusCDE/rmButtonToggler#1]
I apologize for coming with this again, but this time I think there might be something with the executable in the release.

When I run it, it doesn't seem to recognize it as executable. I tried to download it again already.

Some info:
```
-rwxr-xr-x    1 root     root          7456 Dec 28 07:22 button_toggler
-rw-r--r--    1 root     root         68805 Dec 28 07:18 button_toggler.service
-rwxr-xr-x    1 root     root         11328 Dec 26 07:43 touchToggler
-rw-r--r--    1 root     root           157 Dec 26 14:00 touchToggler.service
remarkable: ~/ ./button_toggler 
bash: ./button_toggler: No such file or directory
```

Any idea?

PS: unrelated to this, but a small note. On the docs of both pages the suggested path for the service file is: **/etc/system/systemd/**
but on my remarkable it is: **/etc/systemd/system/**

**Comment by LinusCDE** [comment]
Hi. Sorry, that was actually my bad.

I had compiled the binary on the device using gcc.
The problem is that this gcc was installed using entware. By default the file gets dynamically linked, meaning it relies on external libraries (.so) in specific locations. Since entware is something like a second user space in /opt, gcc links to those libraries in /opt which doesn't exist on devices without [remarkable_entware](https://github.com/Evidlo/remarkable_entware).

The annoying seeming error "No such file or directory" is related to the linker not finding a neccessary file (*/opt/lib/ld-linux.so.3* in this case).
```
$ file button_toggler
button_toggler: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /opt/lib/ld-linux.so.3, for GNU/Linux 3.2.0, not stripped
```

I had that error, too when starting out compiling binaries on the device and that error also let me guess, that the file somehow didn't exist or wasn't executable. Just a confusing message.

I added a new release, that was compiled using the [cross-compiler](https://remarkable.engineering/) (oecore).
I haven't tried the file. Please report if it does, so I (or you) can close this issue.

---

> PS: unrelated to this, but a small note. On the docs of both pages the suggested path for the service file is: /etc/system/systemd/
> but on my remarkable it is: /etc/systemd/system/

Yeah, that's a typo on my side. I fixed that, too.

Edit: Grammar and added link
Edit 2: Also fixed the typo in [rmTouchToggler](https://github.com/LinusCDE/rmTouchToggler).

**Comment by moovida** [comment]
Thanks a ton @LinusCDE , this now works as expected and is a fantastic thing to have!
